[project]
name = "fincolqwen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "byaldi>=0.0.7",
    "claudette>=0.1.4",
    "dotenv>=0.9.9",
    "jupyter>=1.1.1",
    "opencv-python>=4.11.0.86",
    "torch>=2.6.0",
]
